<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\I\PPWCode.Vernacular.EntityFrameworkCore.I.csproj" />
    </ItemGroup>

</Project>
