<Project Sdk="Microsoft.NET.Sdk">
    <!-- ... -->

    <ItemGroup>
        <!-- nuget package dependencies -->
        <PackageReference Include="PPWCode.Vernacular.EntityFrameworkCore.I" Version="1.0.0" />
        <PackageReference Include="PPWCode.Vernacular.EntityFrameworkCore.I.SqlServer" Version="1.0.0" />
    </ItemGroup>

    <!-- ... -->
</Project>
