= About

The `PPWCode.Vernacular.EntityFrameworkCore.I` project is part of the .NET PPWCode project and offers an implementation of `PPWCode.Vernacular.Persistence.V` with support for relational databases Microsoft SQL Server and PostgreSQL.

This library is supported on .NET SDK versions that are currently supported by Microsoft as part of their official support lifecycle.

Note that this project contains the following libraries (and NuGet packages):

- `PPWCode.Vernacular.EntityFrameworkCore.I`, base functionality and database independent abstractions
- `PPWCode.Vernacular.EntityFrameworkCore.I.SqlServer`, support for Microsoft SQL Server
- `PPWCode.Vernacular.EntityFrameworkCore.I.PostgreSQL`, support for PostgreSQL

These libraries are always released as a set and follow the same versioning.  Do not mix different versions of these libraries within the same project.


== Development

Development of the PPWCode is done on https://github.com/peopleware/net-ppwcode-vernacular-entityframeworkcore/tree/I/next[GitHub].

Releases (both stable and pre-release) are published on https://www.nuget.org/packages/PPWCode.Vernacular.EntityFrameworkCore.I/[NuGet] by https://www.nuget.org/profiles/PeopleWare[PeopleWare].


== License and Copyright

Copyright 2024–2026 by xref:ppwcode-net:ROOT:peopleware.adoc[PeopleWare].

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
